---
# Spin_docker role tasks

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- include: install_docker.yml
- include: install_spin_docker.yml
- include: install_celery.yml
- include: install_gunicorn.yml
- include: install_nginx.yml
- include: pull_images.yml
